import { createId } from '@/utils/id'
import type { SupportTicket } from './types'

export const mockSupportTickets: SupportTicket[] = [
  {
    id: createId(),
    ref: 'TKT-1042',
    subject: 'Invoice not generated for March subscription',
    requesterName: 'Bright Smile Dental',
    requesterEmail: 'billing@brightsmile.com',
    category: 'billing',
    priority: 'high',
    status: 'open',
    createdAt: '2026-05-12T09:24:00Z',
    updatedAt: '2026-05-12T09:24:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'Bright Smile Dental',
        text: 'Our March subscription was charged but no invoice appeared in the billing section. We need it for accounting.',
        sentAt: '2026-05-12T09:24:00Z',
      },
    ],
  },
  {
    id: createId(),
    ref: 'TKT-1041',
    subject: 'Cannot add new staff member to clinic',
    requesterName: 'Harbor Wellness',
    requesterEmail: 'admin@harborwellness.com',
    category: 'technical',
    priority: 'urgent',
    status: 'in_progress',
    createdAt: '2026-05-11T14:05:00Z',
    updatedAt: '2026-05-12T08:10:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'Harbor Wellness',
        text: 'The "Add Staff" button shows an error every time we submit the form.',
        sentAt: '2026-05-11T14:05:00Z',
      },
      {
        id: createId(),
        sender: 'support',
        authorName: 'Support Team',
        text: 'Thanks for reporting. We are investigating the issue and will update you shortly.',
        sentAt: '2026-05-12T08:10:00Z',
      },
    ],
  },
  {
    id: createId(),
    ref: 'TKT-1038',
    subject: 'Request to upgrade to the Premium annual plan',
    requesterName: 'Northside Physio',
    requesterEmail: 'contact@northsidephysio.com',
    category: 'account',
    priority: 'medium',
    status: 'open',
    createdAt: '2026-05-10T11:40:00Z',
    updatedAt: '2026-05-10T11:40:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'Northside Physio',
        text: 'We would like to move from the monthly Basic plan to the Premium annual plan. How do we proceed?',
        sentAt: '2026-05-10T11:40:00Z',
      },
    ],
  },
  {
    id: createId(),
    ref: 'TKT-1033',
    subject: 'Coupon code WELCOME20 not applying at checkout',
    requesterName: 'City Care Center',
    requesterEmail: 'support@citycare.com',
    category: 'billing',
    priority: 'medium',
    status: 'resolved',
    createdAt: '2026-05-06T16:20:00Z',
    updatedAt: '2026-05-08T10:00:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'City Care Center',
        text: 'The WELCOME20 coupon shows "invalid" when we try to subscribe.',
        sentAt: '2026-05-06T16:20:00Z',
      },
      {
        id: createId(),
        sender: 'support',
        authorName: 'Support Team',
        text: 'The coupon was restricted to annual plans. We have extended it to monthly plans as well — please try again.',
        sentAt: '2026-05-07T09:15:00Z',
      },
      {
        id: createId(),
        sender: 'requester',
        authorName: 'City Care Center',
        text: 'Works now, thank you!',
        sentAt: '2026-05-08T10:00:00Z',
      },
    ],
  },
  {
    id: createId(),
    ref: 'TKT-1029',
    subject: 'Add export to PDF for transaction history',
    requesterName: 'GreenLeaf Medical',
    requesterEmail: 'it@greenleafmedical.com',
    category: 'feature_request',
    priority: 'low',
    status: 'closed',
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-05-04T12:30:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'GreenLeaf Medical',
        text: 'It would help a lot if we could export the transaction history as a PDF.',
        sentAt: '2026-05-01T08:00:00Z',
      },
      {
        id: createId(),
        sender: 'support',
        authorName: 'Support Team',
        text: 'Great suggestion — we have logged this for a future release. Closing this ticket for now.',
        sentAt: '2026-05-04T12:30:00Z',
      },
    ],
  },
  {
    id: createId(),
    ref: 'TKT-1024',
    subject: 'Password reset email not received',
    requesterName: 'Sunrise Family Clinic',
    requesterEmail: 'frontdesk@sunrisefamily.com',
    category: 'account',
    priority: 'high',
    status: 'in_progress',
    createdAt: '2026-04-28T13:12:00Z',
    updatedAt: '2026-04-29T09:45:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'Sunrise Family Clinic',
        text: 'Our clinic admin requested a password reset three times but never received the email.',
        sentAt: '2026-04-28T13:12:00Z',
      },
      {
        id: createId(),
        sender: 'support',
        authorName: 'Support Team',
        text: 'We found the emails were going to spam. We have whitelisted our domain — could you confirm if it arrives now?',
        sentAt: '2026-04-29T09:45:00Z',
      },
    ],
  },
  {
    id: createId(),
    ref: 'TKT-1019',
    subject: 'General question about Zealth AI usage limits',
    requesterName: 'Riverside Health',
    requesterEmail: 'hello@riversidehealth.com',
    category: 'general',
    priority: 'low',
    status: 'resolved',
    createdAt: '2026-04-22T10:30:00Z',
    updatedAt: '2026-04-23T15:00:00Z',
    messages: [
      {
        id: createId(),
        sender: 'requester',
        authorName: 'Riverside Health',
        text: 'Is there a monthly cap on how many Zealth AI summaries we can generate?',
        sentAt: '2026-04-22T10:30:00Z',
      },
      {
        id: createId(),
        sender: 'support',
        authorName: 'Support Team',
        text: 'On the Premium plan there is no cap. The Basic plan is limited to 200 summaries per month.',
        sentAt: '2026-04-23T15:00:00Z',
      },
    ],
  },
]
